name: Deploy

on:
  push:
      branches:
        - main
  workflow_dispatch:

jobs:
  main:

      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v2
      - name: Obtain keys
        run: |
          (curl https://hyrule-compendium-bot.herokuapp.com -H "Authorization: ${{ secrets.BOT_AUTH }}") > secret
          ls
          sudo chmod 600 secret
      - name: SSH Tunnel
        run: ssh -o StrictHostKeyChecking=no -i secret ${{ secrets.IP }} "sh deploy.sh"